name: CI/CD React Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Generating package-lock.json
        run: npm install

      - name: Build React app
        run: npm run build
        working-directory: ./../../

      - name: Deploy to VM
        run: |
          rsync -av --delete build/ /var/www/html/  # assuming nginx serves /var/www/html/
