name: CI/CD React Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Build React app
        run: npm run build
        working-directory: ./

      - name: Deploy to VM
        run: |
          rsync -av --delete dist/ /var/www/react-app/  # copy to nginx server

      - name: Restart server
        run: |
          sudo systemctl restart reactserver.service
